### ISSUE TITLE
AutoFixture.NUnit2 broken: missing reference to nunit.core.interfaces

### ISSUE THREAD

**Issue by alastairs** [AutoFixture/AutoFixture#246]
The AutoFixture.NUnit2 NuGet package does not work out of the box - it does not ship the nunit.core.interfaces assembly required for the provided `LocalAddIn` class to compile, nor add it as a reference to the test project to which the package is added.

Furthermore, having added this reference manually to my test project, I find that the tests still fail to run in the ReSharper test runner and in NCrunch, albeit with (seemingly) different reasons. In ReSharper, the tests decorated with the `AutoDataAttribute` are automatically ignored with the message "No arguments were provided", and in NCrunch the project fails to compile with the following error:

```
An error occurred while analysing this project after it was built: System.InvalidCastException: Unable to cast object of type 'MyTestProject.LocalAddin' to type 'NUnit.Core.Extensibility.IAddin'.
   at NUnit.Core.CoreExtensions.InstallAddin(Type type)
   at NUnit.Core.CoreExtensions.InstallAdhocExtensions(Assembly assembly)
   at NUnit.Core.Builders.TestAssemblyBuilder.Load(String path)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, String testName, Boolean autoSuites)
   at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)
   at nCrunch.TestExecution.Frameworks.NUnit.NUnitDynamicTestFinder.FindFrameworkTestsUsingRuntimeInvoke(TestPackage package, ILogger logger, List`1 tests)
   at nCrunch.TestExecution.Frameworks.NUnit.NUnitTestFramework.FindFrameworkTestsInAssembly(ReflectedAssembly assembly, FilePath assemblyFilePath, IList`1 referencedAssemblyFilePaths)
   at nCrunch.TestExecution.TestFinder.FindTestsForFrameworks(ReflectedAssembly assembly, FilePath assemblyFilePath, IList`1 referencedAssemblyFilePaths, TestFrameworkDescription[] frameworks)
   at nCrunch.TestExecution.RemoteTaskRunner.AnalyseAssembly(TestFrameworkDescription[] applicableFrameworks)
```

This compilation error is in spite of the fact that the `LocalAddIn` class derives from `Ploeh.AutoFixture.NUnit2.Addins.Addin`, which does implement `NUnit.Core.Extensibility.IAddin`, and the containing assembly is shipped with the NuGet package and referenced from my test project.

**Comment by moreginger** [comment]
Just ran into this issue myself. To summarize, in order for AutoFixture to work with R# 8.2.3 you must:
* Reference NUnit 2.6.3 in the test assembly (or R# won't find the Addin)
* Add binding redirects (or AutoFixture will be unhappy). Not sure if both core and core.interfaces are needed?
```
      <dependentAssembly>
        <assemblyIdentity name="nunit.core.interfaces" publicKeyToken="96d09a1eb7f44a77" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.3.13283" newVersion="2.6.3.13283" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="nunit.core" publicKeyToken="96d09a1eb7f44a77" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.3.13283" newVersion="2.6.3.13283" />
      </dependentAssembly>
```

I've filed https://youtrack.jetbrains.com/issue/RSRP-432554 to see what they have to say about this.
